export type {
  AddressValidationResult,
  ResolvedAddress,
} from "./public-address/index";
export {
  isResolvedAddressPublic,
  validateHttpPublicAddress,
} from "./public-address/index";
export type {
  EditionValidationMetric,
  EditionValidationOptions,
  EditionValidationReport,
  Severity,
  ValidationIssue,
  ValidationRule,
} from "./edition-validation";
export {
  EDITION_VALIDATION_DEFAULTS,
  formatValidationJson,
  formatValidationText,
  VALIDATION_RULES,
  validateEdition,
  validateEditionArtifacts,
} from "./edition-validation";
export type {
  ContentStagingOptions,
  ContentStagingPlan,
  ContentStagingReport,
  StagedContentIndex,
  StagedContentIndexArtifact,
  StagedContentIndexManifest,
  StagedEditionArtifact,
  StagingArtifact,
} from "./content-staging";
export {
  buildStagedContentIndexManifest,
  CONTENT_STAGING_DEFAULTS,
  planContentStaging,
  planWithheldSampleRemovals,
} from "./content-staging";
export type {
  ActiveSource,
  ActiveSourceId,
  FeedFetchMeasurement,
  FeedFetchReport,
  FeedFetchResult,
  FeedFormat,
  FetchFeedOptions,
  HttpFetcher,
  LanguageCode,
  NetworkAddressResolver,
  ParsedFeed,
  ParsedFeedItem,
  PoliticalBias,
  RawRssItem,
  SourceFrequency,
  SourceRecord,
  SourceRegistry,
  SourceRegistryEntry,
  SourceRegistryReport,
  SourceRegistryValidationIssue,
  SourceScope,
  SourceTier,
  SourceType,
} from "./source-registry";
export {
  buildSourceRegistryReport,
  DEFAULT_MAX_REDIRECTS,
  DEFAULT_MAX_RESPONSE_BYTES,
  DEFAULT_REQUEST_TIMEOUT_MS,
  FEED_FETCH_REPORT_VERSION,
  fetchFeedSource,
  formatSourceRegistryJson,
  formatSourceRegistryText,
  parseSourceRegistry,
  parseSourceRegistryYaml,
  SOURCE_REGISTRY_CLI_EXIT_CODES,
  SOURCE_REGISTRY_REPORT_VERSION,
  SOURCE_REGISTRY_SCHEMA_VERSION,
  validateActiveSources,
  validateSourceRegistry,
} from "./source-registry";
export type {
  AllowedHostValidationOptions,
  FeedFetcherOptions,
  FeedFetcherReport,
  FeedFetcherSummary,
  FetchFeedItemsResult,
  SourceFeedItem,
  SourceFetchOptions,
  SourceFetchReport,
  SourceFetchResult,
  SourceItemsFetchReport,
  SourceItemsFetchSummary,
  ValidatedFeedItem,
  ValidatedFeedResult,
} from "./source-fetching";
export {
  DEFAULT_FEED_FETCHER_OPTIONS,
  DEFAULT_SOURCE_FETCH_OPTIONS,
  extractFeedItems,
  fetchFeed,
  fetchSources,
  isAllowedSourceUrl,
  isFeedItemInPublicationWindow,
  parseRssXml,
  validateFeedItem,
} from "./source-fetching";
export type {
  FeedItemNormalizationOptions,
  NormalizedFeedItem,
} from "./feed-normalization";
export {
  canonicalizeStoryUrl,
  createContentHash,
  FEED_ITEM_NORMALIZATION_DEFAULTS,
  normalizeFeedDate,
  normalizeFeedItem,
  normalizeFeedItems,
  sanitizeHtmlToText,
} from "./feed-normalization";
export type {
  EvaluateSourceHealthOptions,
  FetchSourcesCommand,
  FetchSourcesCommandError,
  FetchSourcesCommandResult,
  SourceFetchMeasurement,
  SourceFetchResultInput,
  SourceHealthRecord,
  SourceHealthReport,
  SourceHealthStatus,
  SourceHealthThresholds,
  SourceHealthWarning,
  SourceHealthWarningRule,
} from "./source-health";
export {
  evaluateSourceHealth,
  formatSourceHealthJson,
  formatSourceHealthMarkdown,
  formatSourceHealthText,
  parseFetchSourcesCommand,
  SOURCE_HEALTH_DEFAULTS,
} from "./source-health";
export type {
  DeduplicationOptions,
  DuplicateMatchResult,
  ExactDuplicateReason,
  GoldenDuplicateTestCase,
  TitleTokens,
} from "./deduplication";
export {
  calculateDiceCoefficient,
  calculateTimeDeltaHours,
  calculateTitleSimilarity,
  classifyDuplicate,
  cleanTitle,
  DEDUPLICATION_DEFAULTS,
  findCommonTokens,
  getExactDuplicateReason,
  GOLDEN_DUPLICATE_DATASET,
  hasNumericConflict,
  isExactDuplicate,
  isNearDuplicate,
  tokenizeTitle,
} from "./deduplication";
export type {
  ClusteringOptions,
  ClusterMergeReason,
  ClusterMergeReasonType,
  RepresentativeTitleResult,
  SemanticClusteringProvider,
  SemanticMergeDecision,
  StoryCluster,
} from "./clustering";
export {
  clusterFeedItems,
  clusterFeedItemsAsync,
  CLUSTERING_DEFAULTS,
  NoopSemanticClusteringProvider,
  selectRepresentativeTitle,
} from "./clustering";
export type {
  CandidateFeatureScores,
  CandidateRankingResult,
  FeatureWeights,
  RankedStoryCandidate,
  RankingOptions,
  SelectionDecisionReason,
  SelectionDecisionType,
  SelectionReasonCode,
} from "./candidate-ranking";
export {
  calculateCompositeScore,
  calculateCorroborationScore,
  calculateIndiaRelevanceScore,
  calculateRecencyScore,
  calculateRepetitionPenalty,
  calculateSourceTierScore,
  calculateTopicWeight,
  classifyStoryTopic,
  composeEditionCandidates,
  RANKING_DEFAULTS,
  rankAndComposeCandidates,
} from "./candidate-ranking";
export type {
  PromptExtractedFacts,
  PromptSummaryResult,
  SentenceWithSources,
  StorySummarizer,
  StorySummarizerInput,
  StorySummarizerOutput,
  SummarizerConfig,
  SummarizerOptions,
} from "./summarization";
export {
  CloudflareWorkersAiSummarizer,
  compileSummarizePrompt,
  convertPromptResultToStory,
  createSummarizer,
  DeterministicFallbackSummarizer,
  parsePromptSummaryResult,
  promptSummaryResultSchema,
  SUMMARIZE_PROMPT_VERSION,
  SUMMARIZER_DEFAULTS,
} from "./summarization";
export type {
  FactualExtractedTokens,
  FactualFinding,
  FactualFindingJson,
  FactualFindingSeverity,
  FactualRuleId,
  FactualValidationOptions,
  FactualValidationReport,
  FactualValidationReportJson,
  StoryFactualValidation,
  StoryFactualValidationJson,
} from "./factual-validation";
export {
  checkDateContainment,
  checkEditorialAlignment,
  checkEntityContainment,
  checkNumberContainment,
  checkSourceAttribution,
  checkUncertaintyOnConflict,
  extractDates,
  extractFactTokens,
  extractNamedEntities,
  extractNumbers,
  FACTUAL_VALIDATION_DEFAULTS,
  formatFactualValidationMarkdown,
  formatFactualValidationText,
  getStoryFullText,
  normalizeNumberToken,
  toFactualValidationReportJson,
  validateFactualSupport,
  validateStoryFactualSupport,
} from "./factual-validation";
